GAS_TYPES = {
	smoke = {
		factory = prism.actors.Smoke,
		index = 178,
		keepRatio = 0.95,
		spreadRadio = 0.05 / 8,
		reduceRatio = 0.9,
		minimumVolume = 0.4,
		threshold = 4.0,
		fg = prism.Color4.TRANSPARENT,
		bgFull = prism.Color4.GREY,
		bgFading = prism.Color4.DARKGREY,
		spreadDamage = 0,
		scorchColor = nil,
		scorchIntensity = nil,
		cellDamage = 0,
	},
	fire = {
		factory = prism.actors.Fire,
		keepRatio = 0.5,
		spreadRadio = 1.0 / 8,
		reduceRatio = 0.9,
		minimumVolume = 0.5,
		threshold = 4.0,
		fg = prism.Color4.TRANSPARENT,
		bgFull = prism.Color4.RED,
		bgFading = prism.Color4.YELLOW,
		spreadDamage = 0,
		scorchIntensity = 0.1,
		scorchColor = prism.Color4.DARKGREY,
		cellDamage = 5,
	},
}
